spring:
  datasource:
    url: jdbc:mysql://10.34.37.190:3306/sell?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123456
server:
  servlet:
    context-path: /sell
